AWSTemplateFormatVersion: "2010-09-09"

Parameters: 
  Stage:
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - qa
      - demo
      - prod
  ProjectName:
    Type: String

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Stage}-assets-bucket-${ProjectName}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  s3Bucket:
    Description: The name of the bucket
    Value: !GetAtt s3Bucket.Arn
    Export: 
      Name: !Sub ${AWS::StackName}-assets-bucket